CREATE TABLE BOARD (
  ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
  TITLE     VARCHAR(200),
  DESC      VARCHAR(4000),
  CREATE_ID VARCHAR(20),
  CREATE_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MODIFIER_ID VARCHAR(20),
  MODIFIER_DT TIMESTAMP
);

INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목1', '내용1', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목2', '내용2', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목3', '내용3', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목4', '내용4', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목5', '내용5', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목6', '내용6', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목7', '내용7', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목8', '내용8', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목9', '내용9', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목10', '내용10', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목11', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목12', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목13', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목14', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목15', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목16', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목17', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목18', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목19', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목20', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목21', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목22', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목23', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목24', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목25', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목26', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목27', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목28', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목29', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목30', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목31', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목32', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목33', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목34', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목35', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목36', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목37', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목38', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목39', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목40', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목41', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목42', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목43', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목44', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목45', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목46', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목47', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목48', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목49', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목50', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목51', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목52', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목53', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목54', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목55', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목56', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목57', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목58', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목59', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목60', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목61', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목62', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목63', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목64', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목65', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목66', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목67', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목68', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목69', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목70', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목71', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목72', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목73', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목74', '내용11', CURRENT_TIMESTAMP());
INSERT INTO BOARD (TITLE, DESC, CREATE_DT) VALUES ('제목75', '내용11', CURRENT_TIMESTAMP());